integrations:
  rescue-time:
    overview: true
    top-categories: true
    top-activities: false
  last-fm:
    all: true
  pocket-casts:
    all: true
  wakatime:
    all: true
  google-fit:
    all: true
  oura-ring:
    all: true
  # clockify:
  # spotify:
  # goodreads:
